### ISSUE TITLE
Add a `--background` option to `rasactl connect rasa`

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasactl#13]
`rasactl connect rasa` starts a rasa server in the foreground, so if you close the terminal, your server dies.
Would be helpful to have a `--background` flag so `rasactl connect rasa --background`  starts a rasa server in the background independent of terminal session.

**Comment by tmbo** [comment]
@melindaloubser1 can you add a bit more clarity on the use case? what are you trying to do as a user (as in, how does this fit into the larger workflow you are trying to achieve)?

@tczekajlo what do you think, is this something we should support?

**Comment by melindaloubser1** [comment]
As a user, I want to run Rasa X locally with Rasa attached, for an extended (few days let's say) period of time. I don't want the  Rasa server to stop each time I close my terminal. I can kind of do this with a `& disown` but it's cleaner if it's part of the command, esp. if you can `rasactl disconnect rasa` and it kills the background process.

**Comment by tczekajlo** [comment]
@tmbo Yes, i think it's something that can be helpful, and we should add it.

**Comment by andreoid** [comment]
Migrated issue to JIRA: https://rasahq.atlassian.net/browse/INFRA-14
