### ISSUE TITLE
Add additional deployment statuses

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/rasactl#14]
### What problem are you trying to solve?

Currently, if Rasa X is deploying or upgrading a deployment, `rasactl status/list` returns status for a given deployment as `Stopped`. 

### What's your suggested solution?

Add separate statuses for installing deployment and upgrading.

**Comment by tmbo** [comment]
in terms of feasibility, how easy and available is the information we need to show an instance as "upgrading"?
