### ISSUE TITLE
`~/.kube/config` file is missing

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasactl#2]
I just got this error after following the [installation instructions](https://github.com/RasaHQ/rasactl/tree/init#development) in the `init` branch. 

```
(venv) ➜  rasactl git:(init) ✗ sudo ./rasactl start -p
Error: stat /root/.kube/config: no such file or directory
stat /root/.kube/config: no such file or directory
```

It seems like for local mode I need a `~/.kube/config` file around? If that's the case, it would be good to add a section in the installation guide on how to add it. I imagine this is a file that's known for kubernetes users, but since  kubernetes novices will also need to use this tool I'd argue we need to add a step to the installation guide.

**Comment by melindaloubser1** [comment]
@tczekajlo I'm still prompted for my password when using  and it still shows the message "sudo is required". Did it change back?

**Comment by tczekajlo** [comment]
@melindaloubser1 no, `sudo` is not required anymore, which version do you use?

**Comment by melindaloubser1** [comment]
I followed the docs just yesterday, so whichever version `curl -O https://rei.rasa.com/rei.sh && bash rei.sh -y` gives you
