### ISSUE TITLE
Cannot connect to a local rasa open source server

### ISSUE THREAD

**Issue by TRoboto** [RasaHQ/rasactl#22]
**Describe the bug**

I get the following error message when running `rasactl connect rasa`.

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/RasaHQ/rasactl/pkg/k8s.(*Kubernetes).GetRabbitMqCreds(0xc0004a6500)
        /go/src/rasactl/pkg/k8s/secrets.go:127 +0x23a
github.com/RasaHQ/rasactl/pkg/rasactl.(*RasaCtl).saveRasaEndpointsFile(0xc0004a6280, {0xc0010fe840, 0x20})
        /go/src/rasactl/pkg/rasactl/connect_rasa.go:280 +0x12b
github.com/RasaHQ/rasactl/pkg/rasactl.(*RasaCtl).ConnectRasa(0xc0004a6280)
        /go/src/rasactl/pkg/rasactl/connect_rasa.go:142 +0xdc9
github.com/RasaHQ/rasactl/cmd.connectRasaCmd.func2(0xc00029bb80, {0xc0000b8d20, 0x1, 0x3})
        /go/src/rasactl/cmd/connect_rasa.go:117 +0xab
github.com/spf13/cobra.(*Command).execute(0xc00029bb80, {0xc0000b8c90, 0x3, 0x3})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x3eff7e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/RasaHQ/rasactl/cmd.Execute()
        /go/src/rasactl/cmd/root.go:75 +0x25
main.main()
        /go/src/rasactl/main.go:32 +0xc5
```

**To Reproduce**
1. Install Rasa X following the docs [here](https://rasa.com/docs/rasa-x/installation-and-setup/install/rasa-ephemeral-installer/installation#quickstart).
2. Install rasa with `pip install rasa`.
3. Create new project with `rasa init` and cd to the project.
4. Run `rasactl connect rasa` and see the output error.

**Expected behavior**
Rasa X should connect to Rasa OSS successfully.

**Desktop (please complete the following information):**
 - OS: VM with Ubuntu 20.04 (4vCPU and 16GB RAM).

**rasactl version***
rasactl version 1.0.0

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tczekajlo** [comment]
@TRoboto The issue was fixed in the https://github.com/RasaHQ/rasactl/pull/23. The 1.0.1 version includes the fix.
