### ISSUE TITLE
rasactl should use the latest rasa-x-helm by default

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasactl#32]
### What problem are you trying to solve?

In rasactl 1.0.2, `rasactl start -h` shows:

![image](https://user-images.githubusercontent.com/2398765/151229224-7c5f2f87-f04e-4665-a4e8-ba9123190057.png)

at the time of writing, the latest rasa-x helm chart is 4.3.2.

rasactl should automatically use the latest rasa-x helm chart so that customers are able to use the latest features and not get stuck troubleshooting a bug that was already fixed in a subsequent release.

### What's your suggested solution?

rasactl should always use the latest rasa-x helm release

### Definition of Done

rasactl  uses the latest rasa-x helm release by default

**Comment by andreoid** [comment]
Enhancement request moved to JIRA: https://rasahq.atlassian.net/browse/INFRA-11
