### ISSUE TITLE
[`connect rasa`] Add support for action endpoint

### ISSUE THREAD

**Issue by tczekajlo** [RasaHQ/rasactl#35]
### What problem are you trying to solve?

Currently, the `connect rasa` doesn't support Rasa Action Server. 

### Definition of Done

The `connect rasa` supports Action Server.

**Comment by andreoid** [comment]
Migrated to JIRA: INFRA-15

**Comment by LeonardMF** [comment]
Hey @andreoid , could you please give an update on the ticket INFRA-15 and maybe give an outlook, when the `connect rasa` supports Action Server.

**Comment by edunuzzi** [comment]
If anyone is trying to use a custom action server when running `rasactl connect rasa`, here is what I had to do:

1. Run `rasactl connect rasa` as you normally would - it will ignore your local `endpoints.yml` and create a `/tmp/rasactl-<replace this with the generated namespace>/.endpoints.yaml`
2. Edit the newly created endpoints file mentioned above to include:
```
action_endpoint:
    url: <your custom action server url>
```
3. Find the pid for the running rasa with something like `ps -ef | grep rasa` and kill it. The command should be something similar to this:
`/usr/bin/python3 /usr/local/bin/rasa run --verbose --enable-api --cors '*' --auth-token <someRandomToken> --credentials /tmp/rasactl-funny-lichterman/.credentials.yaml --endpoints /tmp/rasactl-funny-lichterman/.endpoints.yaml -p 5005`
4. Run the command that you killed in the previous step.

Not an ideal solution, but hopefully this will save some time for someone. :)

**Comment by lichenglu** [comment]
> If anyone is trying to use a custom action server when running `rasactl connect rasa`, here is what I had to do:
> 
> 1. Run `rasactl connect rasa` as you normally would - it will ignore your local `endpoints.yml` and create a `/tmp/rasactl-<replace this with the generated namespace>/.endpoints.yaml`
> 2. Edit the newly created endpoints file mentioned above to include:
> 
> ```
> action_endpoint:
>     url: <your custom action server url>
> ```
> 
> 3. Find the pid for the running rasa with something like `ps -ef | grep rasa` and kill it. The command should be something similar to this:
>    `/usr/bin/python3 /usr/local/bin/rasa run --verbose --enable-api --cors '*' --auth-token <someRandomToken> --credentials /tmp/rasactl-funny-lichterman/.credentials.yaml --endpoints /tmp/rasactl-funny-lichterman/.endpoints.yaml -p 5005`
> 4. Run the command that you killed in the previous step.
> 
> Not an ideal solution, but hopefully this will save some time for someone. :)

Thanks for the generous sharing! In my case, the generated `endpoint` file was named as `.endpoint.yaml` under the `PROJECY_DIRECTORY`. The team might have changed the behavior. Other than this, I got to make the custom action server up and running following your suggestions.
