### ISSUE TITLE
How to access Rasa X web interface?

### ISSUE THREAD

**Issue by nguyenhuuthuat09** [RasaHQ/rasactl#46]
Hi, I am just deploy my Rasa X server on my server. It give me a `random URL` like example below.

```
$ rasactl status vibrant-yalow
Name:                   	vibrant-yalow
Status:                 	Running
URL:                    	http://vibrant-yalow.rasactl.localhost
Version:                	0.42.0
Enterprise:             	inactive
Rasa production version:	2.8.1
Rasa worker version:    	2.8.1
Project path:           	/home/ubuntu/test
```
But I can not access it by `URL:  http://vibrant-yalow.rasactl.localhost`. How can I 

Thank you so much and have a great day!

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by hsm207** [comment]
what happens when you try to  go to the url?

**Comment by nguyenhuuthuat09** [comment]
Hi, when I tried to go to the url, It say that "This site can’t be reached. serene-torvalds.rasactl.localhost refused to connect.". But `rasactl start` run successfully.

![Screenshot from 2022-05-06 15-35-10](https://user-images.githubusercontent.com/29718711/167097332-111df092-b30a-4dea-b005-91f0d5ab9067.png)

**Comment by nguyenhuuthuat09** [comment]
I found the way, using `ngrok http --host-header=URL URL`. Thank you for great library.
