### ISSUE TITLE
feature flag --kubeconfig-context 

### ISSUE THREAD

**Issue by RASADSA** [RasaHQ/rasactl#6]
In case the kubeconfig has multiple clusters configured - rasactl selects the last added cluster.

which can lead to false environment deployments.

would be good to introduce a context selector and a check with warning when multiple clusters are configured and none is selected to improve the overall experience and to lower the risk of false deployments.

**Comment by tczekajlo** [comment]
Included in the 0.0.17 version.

**Comment by RASADSA** [comment]
works thx
